Repository sifa123/Dev-Kitchen, pull requests merged in 2021-07, with the labels that each got.

#15 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: DCP21, 🟪 Level0

#16 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: DCP21, 🟪 Level0

#18 Navbar added
  Nav-bar/logo.png
  images/logo.png
  index.html
  styles/index.css
Labels: DCP21, 🟩 Level1

#20 Fav-icon
  images/fav-icon.png
  index.html
Labels: DCP21, 🟪 Level0

#25 added footer
  about.html
  contact.html
  gallery.html
  index.html
  menu.html
  reviews.html
  styles/about.css
  styles/contact.css
  styles/gallery.css
  styles/index.css
  styles/menu.css
  styles/reviews.css
  styles/table-reserv.css
  table-reserv.html
Labels: DCP21, 🟩 Level1

#35 Designed review page
  reviews.html
  styles/reviews.css
Labels: DCP21, 🟩 Level1

#39 added issue and pull request
  .github/issue_template.md
  .github/pull_request_template.md
Labels: DCP21, 🟪 Level0

#57 Dcp21
  about.html
  contact.html
  gallery.html
  images/catering.png
  images/dman.png
  images/free-delivery.png
  images/hero.png
  images/roasted-chicken.png
  images/ug.png
  index.html
  menu.html
  reviews.html
  styles/index.css
  table-reserv.html
Labels: DCP21, 🟨 Level2

#58 Added Scroll To Top Button
  images/scrtotop.jfif
  index.html
  styles/index.css
Labels: DCP21, 🟩 Level1

#59 README.md updated
  README.md
Labels: DCP21

#55 service page
  images/icons8-cooking-pot-50.png
  index.html
  service.html
  styles/service.css
Labels: DCP21, 🟨 Level2

#68 fix: table reservation card
  index.html
  styles/index.css
Labels: DCP21, 🟩 Level1
